handle_signals: handle_signals.o
	gcc -Wall -ggdb handle_signals.o -o handle_signals
handle_signals.o: handle_signals.c
	gcc -Wall -ggdb -c handle_signals.c -o handle_signals.o

clean: 
	rm handle_signals.o handle_signals
